name: Deploy Flask App on VPS (Wrapper)
on:
  push:
    branches:
      - init
      - infra
      - init-infra

jobs:
  run:
    uses: ./.github/workflows/deploy-flask-app.yml
    with:
      runner: ${{ vars.SELF_HOSTED == 'true' && 'self-hosted' || 'ubuntu-latest' }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

# NOTES:
# 1) use init branch to run in app-mode (i.e. only deploys app)
# 2) use *infra branches to run in infra-mode (i.e. configures infrastructure + deploys app)
# 3) set the `SELF_HOSTED` variable to `true` in your repository settings to enable self-hosted runners.
# 4) workflow used for deploying only fresh app on either fresh or existing VPS.
