name: Update Flask App on VPS
on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true

jobs:
  update:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Retrieve App Name
        run: |
          REPO_FULL_NAME="${{ github.repository }}"
          APP_NAME="${REPO_FULL_NAME#*/}"
          echo "APP_NAME=$APP_NAME" >> "$GITHUB_ENV"

      - name: Update App on VPS
        env:
          BRANCH: ${{ github.ref_name }}
          REPO_URL: https://github.com/${{ github.repository }}.git
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_USER: ${{ vars.VPS_USER }}
          VPS_HOST: ${{ vars.VPS_HOST }}
          SCRIPT_PATH: ${{ vars.SCRIPTS_DIR }}/update-app.sh
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key
          ssh -i ssh_key -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST \
            "$SCRIPT_PATH $APP_NAME $BRANCH $REPO_URL"
