name: Update Flask App on VPS (Wrapper)
on:
  push:
    branches:
      - update

jobs:
  run:
    uses: ./.github/workflows/update-flask-app.yml
    with:
      runner: ${{ vars.SELF_HOSTED == 'true' && 'self-hosted' || 'ubuntu-latest' }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

# NOTES:
# 1) set the `SELF_HOSTED` variable to `true` in your repository settings to enable self-hosted runners.
# 2) workflow used for updating existing app on existing VPS only.
